[project]
name = "cold-archiver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.20.0",
    "minio==7.2.20",
    "sqlalchemy>=2.0.54",
]

[project.scripts]
cold-archiver = "cold_archiver:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.8",
]
